/* The following code was generated by JFlex 1.4.3 on 31/05/22 04:47 PM */

package SoloLexico;
import static SoloLexico.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 31/05/22 04:47 PM from the specification file
 * <tt>../SoloLexico_Basico/src/SoloLexico/Lexico.flex</tt>
 */
class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\21\2\0\1\3\22\0\1\3\1\40\1\22\1\44"+
    "\4\0\1\45\1\46\1\37\1\35\1\51\1\36\1\50\1\20\12\2"+
    "\1\0\1\47\1\34\1\33\1\32\2\0\22\1\1\11\7\1\1\25"+
    "\1\0\1\26\1\0\1\1\1\0\1\7\1\4\1\16\1\27\1\6"+
    "\1\30\1\15\1\1\1\13\1\1\1\10\1\31\1\43\1\14\1\23"+
    "\2\1\1\5\1\17\1\12\1\24\5\1\1\41\1\0\1\42\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\7\2\1\5\1\6"+
    "\1\7\1\10\1\11\2\2\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\1\1\20\1\21\1\2\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\0\6\2\1\30\2\2"+
    "\1\4\1\31\1\2\1\32\2\2\1\33\1\34\1\35"+
    "\1\36\1\37\1\0\1\40\1\41\1\2\1\3\5\2"+
    "\1\42\6\2\1\43\1\0\3\2\1\44\1\2\1\45"+
    "\1\2\1\46\6\2\1\0\1\3\1\47\1\50\4\2"+
    "\1\51\3\2\1\52\1\0\1\53\1\54\3\2\1\55"+
    "\1\56\1\3\1\57\1\2\1\60\1\61";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\52\0\124\0\176\0\250\0\322\0\374\0\u0126"+
    "\0\u0150\0\u017a\0\u01a4\0\u01ce\0\u01f8\0\52\0\52\0\52"+
    "\0\52\0\u0222\0\u024c\0\u0276\0\u02a0\0\u02ca\0\u02f4\0\u031e"+
    "\0\u0348\0\u0372\0\52\0\52\0\u039c\0\52\0\52\0\52"+
    "\0\52\0\52\0\52\0\u03c6\0\u03f0\0\u041a\0\u0444\0\u046e"+
    "\0\u0498\0\u04c2\0\124\0\u04ec\0\u0516\0\u0540\0\52\0\u056a"+
    "\0\u0594\0\u05be\0\u05e8\0\52\0\52\0\52\0\52\0\52"+
    "\0\u0612\0\52\0\52\0\u063c\0\u03c6\0\u0666\0\u0690\0\u06ba"+
    "\0\u06e4\0\u070e\0\124\0\u0738\0\u0762\0\u078c\0\u07b6\0\u07e0"+
    "\0\u080a\0\124\0\u0834\0\u085e\0\u0888\0\u08b2\0\124\0\u08dc"+
    "\0\124\0\u0906\0\124\0\u0930\0\u095a\0\u0984\0\u09ae\0\u09d8"+
    "\0\u0a02\0\u0a2c\0\u0a2c\0\124\0\124\0\u0a56\0\u0a80\0\u0aaa"+
    "\0\u0ad4\0\124\0\u0afe\0\u0b28\0\u0b52\0\124\0\u0b7c\0\124"+
    "\0\124\0\u0ba6\0\u0bd0\0\u0bfa\0\124\0\124\0\52\0\124"+
    "\0\u0c24\0\124\0\124";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\3"+
    "\1\11\1\12\1\13\2\3\1\14\1\3\1\15\1\16"+
    "\1\17\2\3\1\20\1\21\1\22\1\23\1\3\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\53\0"+
    "\2\3\1\0\14\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\6\0\2\44\1\4\16\44\1\0\30\44\3\0"+
    "\1\5\47\0\2\3\1\0\1\3\1\45\12\3\3\0"+
    "\2\3\2\0\3\3\11\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\46\11\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\7\0\2\3\1\0\14\3\3\0\2\3\2\0"+
    "\2\3\1\47\11\0\1\3\7\0\2\3\1\0\6\3"+
    "\1\50\5\3\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\1\3\1\51\12\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\7\0\2\3\1\0\10\3"+
    "\1\52\3\3\3\0\2\3\2\0\1\3\1\53\1\3"+
    "\11\0\1\3\7\0\2\3\1\0\3\3\1\54\10\3"+
    "\3\0\1\55\1\3\2\0\3\3\11\0\1\3\26\0"+
    "\1\56\12\0\1\57\17\0\2\3\1\0\2\3\1\60"+
    "\11\3\3\0\1\61\1\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\3\3\1\62\10\3\3\0\1\63"+
    "\1\3\2\0\3\3\11\0\1\3\41\0\1\64\51\0"+
    "\1\65\51\0\1\66\51\0\1\67\20\0\1\4\30\0"+
    "\1\70\11\0\1\71\37\0\1\72\51\0\1\73\17\0"+
    "\2\3\1\0\3\3\1\74\10\3\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\10\0\1\75\50\0\2\3\1\0"+
    "\2\3\1\76\11\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\7\0\2\3\1\0\6\3\1\77\5\3\3\0"+
    "\2\3\2\0\3\3\11\0\1\3\7\0\2\3\1\0"+
    "\13\3\1\100\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\1\3\1\101\12\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\7\0\2\3\1\0\14\3"+
    "\3\0\1\3\1\102\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\6\3\1\103\3\3\1\104\1\3\3\0"+
    "\2\3\2\0\3\3\11\0\1\3\7\0\2\3\1\0"+
    "\13\3\1\105\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\10\3\1\106\3\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\6\0\21\56\1\0\30\56"+
    "\1\0\2\3\1\0\14\3\3\0\2\3\2\0\1\3"+
    "\1\107\1\3\11\0\1\3\7\0\2\3\1\0\14\3"+
    "\3\0\1\3\1\110\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\14\3\3\0\2\3\2\0\2\3\1\111"+
    "\11\0\1\3\7\0\2\3\1\0\1\3\1\112\12\3"+
    "\3\0\2\3\2\0\3\3\11\0\1\3\10\0\1\113"+
    "\50\0\2\3\1\0\7\3\1\114\4\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\7\0\2\3\1\0\3\3"+
    "\1\115\10\3\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\14\3\3\0\1\3\1\116\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\2\3\1\117"+
    "\11\3\3\0\2\3\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\7\3\1\120\4\3\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\2\3\1\121"+
    "\11\3\3\0\2\3\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\14\3\3\0\2\3\2\0\2\3\1\122"+
    "\11\0\1\3\7\0\2\3\1\0\2\3\1\123\11\3"+
    "\3\0\2\3\2\0\3\3\11\0\1\3\7\0\2\3"+
    "\1\0\6\3\1\124\4\3\1\125\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\3\3\1\126"+
    "\3\3\1\127\4\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\7\0\2\3\1\0\1\130\13\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\7\0\2\3\1\0\13\3"+
    "\1\131\3\0\2\3\2\0\3\3\11\0\1\3\6\0"+
    "\2\132\1\113\16\132\1\0\24\132\1\133\3\132\1\0"+
    "\2\3\1\0\10\3\1\134\3\3\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\4\3\1\135"+
    "\7\3\3\0\2\3\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\1\3\1\136\12\3\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\10\3\1\137"+
    "\3\3\3\0\2\3\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\14\3\3\0\1\3\1\140\2\0\3\3"+
    "\11\0\1\3\7\0\2\3\1\0\7\3\1\141\4\3"+
    "\3\0\2\3\2\0\3\3\11\0\1\3\7\0\2\3"+
    "\1\0\6\3\1\142\5\3\3\0\2\3\2\0\3\3"+
    "\11\0\1\3\7\0\2\3\1\0\14\3\3\0\1\3"+
    "\1\143\2\0\3\3\11\0\1\3\7\0\2\3\1\0"+
    "\10\3\1\144\3\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\7\0\2\3\1\0\14\3\3\0\2\3\2\0"+
    "\2\3\1\145\11\0\1\3\7\0\2\3\1\0\2\3"+
    "\1\146\11\3\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\10\0\1\147\50\0\2\3\1\0\10\3\1\150\3\3"+
    "\3\0\2\3\2\0\3\3\11\0\1\3\7\0\2\3"+
    "\1\0\11\3\1\151\2\3\3\0\2\3\2\0\3\3"+
    "\11\0\1\3\7\0\2\3\1\0\14\3\3\0\2\3"+
    "\2\0\1\152\2\3\11\0\1\3\7\0\2\3\1\0"+
    "\10\3\1\153\3\3\3\0\2\3\2\0\3\3\11\0"+
    "\1\3\7\0\2\3\1\0\14\3\3\0\2\3\2\0"+
    "\2\3\1\154\11\0\1\3\7\0\2\3\1\0\2\3"+
    "\1\155\11\3\3\0\2\3\2\0\3\3\11\0\1\3"+
    "\7\0\2\3\1\0\2\3\1\156\11\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\10\0\1\147\43\0\1\157"+
    "\4\0\2\3\1\0\2\3\1\160\11\3\3\0\2\3"+
    "\2\0\3\3\11\0\1\3\7\0\2\3\1\0\14\3"+
    "\3\0\1\3\1\161\2\0\3\3\11\0\1\3\7\0"+
    "\2\3\1\0\6\3\1\162\5\3\3\0\2\3\2\0"+
    "\3\3\11\0\1\3\7\0\2\3\1\0\2\3\1\163"+
    "\11\3\3\0\2\3\2\0\3\3\11\0\1\3\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3150];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\13\1\4\11\11\1\2\11\1\1\6\11"+
    "\1\0\12\1\1\11\4\1\5\11\1\0\2\11\17\1"+
    "\1\0\16\1\1\0\14\1\1\0\7\1\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexemas;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 31: 
          { lexemas=yytext(); return MenosIgual;
          }
        case 50: break;
        case 23: 
          { lexemas=yytext(); return Coma;
          }
        case 51: break;
        case 17: 
          { lexemas=yytext(); return Llave_c;
          }
        case 52: break;
        case 35: 
          { lexemas=yytext(); return For;
          }
        case 53: break;
        case 30: 
          { lexemas=yytext(); return MasIgual;
          }
        case 54: break;
        case 7: 
          { lexemas=yytext(); return Comillas;
          }
        case 55: break;
        case 40: 
          { lexemas=yytext(); return Break;
          }
        case 56: break;
        case 41: 
          { lexemas=yytext(); return Const;
          }
        case 57: break;
        case 13: 
          { lexemas=yytext(); return Suma;
          }
        case 58: break;
        case 12: 
          { lexemas=yytext(); return MenorQue;
          }
        case 59: break;
        case 26: 
          { lexemas=yytext(); return Do;
          }
        case 60: break;
        case 6: 
          { return Linea;
          }
        case 61: break;
        case 48: 
          { lexemas=yytext(); return Default;
          }
        case 62: break;
        case 18: 
          { lexemas=yytext(); return Numeral;
          }
        case 63: break;
        case 32: 
          { lexemas=yytext(); return MultiplicacionIgual;
          }
        case 64: break;
        case 36: 
          { lexemas=yytext(); return Else;
          }
        case 65: break;
        case 38: 
          { lexemas=yytext(); return Case;
          }
        case 66: break;
        case 19: 
          { lexemas=yytext(); return Parent_a;
          }
        case 67: break;
        case 33: 
          { lexemas=yytext(); return Diferente;
          }
        case 68: break;
        case 37: 
          { lexemas=yytext(); return True;
          }
        case 69: break;
        case 46: 
          { lexemas=yytext(); return Doble;
          }
        case 70: break;
        case 21: 
          { lexemas=yytext(); return P_coma;
          }
        case 71: break;
        case 24: 
          { lexemas=yytext(); return If;
          }
        case 72: break;
        case 25: 
          { lexemas=yytext(); return DivisionIgual;
          }
        case 73: break;
        case 42: 
          { lexemas=yytext(); return False;
          }
        case 74: break;
        case 43: 
          { lexemas=yytext(); return Return;
          }
        case 75: break;
        case 8: 
          { lexemas=yytext(); return Corchete_a;
          }
        case 76: break;
        case 49: 
          { lexemas=yytext(); return Continue;
          }
        case 77: break;
        case 20: 
          { lexemas=yytext(); return Parent_c;
          }
        case 78: break;
        case 16: 
          { lexemas=yytext(); return Llave_a;
          }
        case 79: break;
        case 2: 
          { lexemas=yytext(); return Identificador;
          }
        case 80: break;
        case 22: 
          { lexemas=yytext(); return Punto;
          }
        case 81: break;
        case 14: 
          { lexemas=yytext(); return Resta;
          }
        case 82: break;
        case 34: 
          { lexemas=yytext(); return Int;
          }
        case 83: break;
        case 28: 
          { lexemas=yytext(); return ComparadorIgual;
          }
        case 84: break;
        case 15: 
          { lexemas=yytext(); return Multiplicacion;
          }
        case 85: break;
        case 39: 
          { lexemas=yytext(); return Main;
          }
        case 86: break;
        case 1: 
          { return ERROR;
          }
        case 87: break;
        case 27: 
          { lexemas=yytext(); return MayorIgual;
          }
        case 88: break;
        case 3: 
          { lexemas=yytext(); return Numero;
          }
        case 89: break;
        case 45: 
          { lexemas=yytext(); return Define;
          }
        case 90: break;
        case 10: 
          { lexemas=yytext(); return MayorQue;
          }
        case 91: break;
        case 5: 
          { lexemas=yytext(); return Division;
          }
        case 92: break;
        case 4: 
          { /*Ignore*/
          }
        case 93: break;
        case 47: 
          { lexemas=yytext(); return Include;
          }
        case 94: break;
        case 9: 
          { lexemas=yytext(); return Corchete_c;
          }
        case 95: break;
        case 11: 
          { lexemas=yytext(); return Igual;
          }
        case 96: break;
        case 44: 
          { lexemas=yytext(); return Cadena;
          }
        case 97: break;
        case 29: 
          { lexemas=yytext(); return MenorIgual;
          }
        case 98: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
