/* The following code was generated by JFlex 1.4.3 on 27/06/22 06:24 PM */

package Analizador;
import static Analizador.Tokens.*;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 27/06/22 06:24 PM from the specification file
 * <tt>../AnalizadorLexico/src/Analizador/Lexico.flex</tt>
 */
class Lexico {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\20\2\0\1\3\22\0\1\3\1\41\1\21\1\54"+
    "\1\0\1\42\1\44\1\0\1\55\1\56\1\40\1\36\1\61\1\37"+
    "\1\60\1\17\12\2\1\43\1\57\1\35\1\34\1\33\2\0\32\1"+
    "\1\24\1\0\1\25\1\0\1\1\1\0\1\7\1\4\1\16\1\26"+
    "\1\6\1\27\1\15\1\32\1\13\1\1\1\10\1\30\1\47\1\14"+
    "\1\22\1\50\1\1\1\5\1\11\1\12\1\23\1\53\1\31\1\1"+
    "\1\46\1\1\1\51\1\45\1\52\uff82\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\10\2\1\4\1\5"+
    "\1\6\1\2\1\7\1\10\4\2\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\2\1\24\1\25\1\2\1\26\1\27\1\30\1\31"+
    "\1\32\1\33\1\0\15\2\1\34\10\2\1\35\5\2"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\1\45"+
    "\1\46\1\0\1\47\1\50\1\51\1\52\1\53\2\2"+
    "\1\3\10\2\1\54\4\2\1\55\4\2\1\56\10\2"+
    "\1\57\3\2\1\0\3\2\1\60\1\61\2\2\1\62"+
    "\1\63\3\2\1\64\4\2\1\65\2\2\1\66\1\67"+
    "\7\2\1\70\1\2\1\0\1\3\1\71\1\72\1\73"+
    "\4\2\1\74\4\2\1\75\1\2\1\76\4\2\1\77"+
    "\1\100\1\101\1\0\1\102\1\2\1\103\1\104\7\2"+
    "\1\105\1\106\1\3\1\2\1\107\1\110\4\2\1\111"+
    "\1\112\1\113\1\2\1\114\1\115\1\116";

  private static int [] zzUnpackAction() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\62\0\144\0\226\0\310\0\372\0\u012c\0\u015e"+
    "\0\u0190\0\u01c2\0\u01f4\0\u0226\0\u0258\0\u028a\0\62\0\62"+
    "\0\u02bc\0\62\0\62\0\u02ee\0\u0320\0\u0352\0\u0384\0\u03b6"+
    "\0\u03e8\0\u041a\0\u044c\0\u047e\0\u04b0\0\u04e2\0\u0514\0\62"+
    "\0\u0546\0\u0578\0\u05aa\0\62\0\62\0\u05dc\0\62\0\62"+
    "\0\62\0\62\0\62\0\62\0\u060e\0\u0640\0\u0672\0\u06a4"+
    "\0\u06d6\0\u0708\0\u073a\0\u076c\0\u079e\0\u07d0\0\u0802\0\u0834"+
    "\0\u0866\0\u0898\0\144\0\u08ca\0\u08fc\0\u092e\0\u0960\0\u0992"+
    "\0\u09c4\0\u09f6\0\u0a28\0\u0a5a\0\u0a8c\0\u0abe\0\u0af0\0\u0b22"+
    "\0\u0b54\0\62\0\62\0\62\0\62\0\62\0\62\0\62"+
    "\0\62\0\62\0\u0b86\0\62\0\62\0\62\0\62\0\62"+
    "\0\u0bb8\0\u0bea\0\u060e\0\u0c1c\0\u0c4e\0\u0c80\0\u0cb2\0\u0ce4"+
    "\0\u0d16\0\u0d48\0\u0d7a\0\144\0\u0dac\0\u0dde\0\u0e10\0\u0e42"+
    "\0\144\0\u0e74\0\u0ea6\0\u0ed8\0\u0f0a\0\144\0\u0f3c\0\u0f6e"+
    "\0\u0fa0\0\u0fd2\0\u1004\0\u1036\0\u1068\0\u109a\0\144\0\u10cc"+
    "\0\u10fe\0\u1130\0\u1162\0\u1194\0\u11c6\0\u11f8\0\144\0\144"+
    "\0\u122a\0\u125c\0\144\0\144\0\u128e\0\u12c0\0\u12f2\0\144"+
    "\0\u1324\0\u1356\0\u1388\0\u13ba\0\144\0\u13ec\0\u141e\0\144"+
    "\0\144\0\u1450\0\u1482\0\u14b4\0\u14e6\0\u1518\0\u154a\0\u157c"+
    "\0\144\0\u15ae\0\u15e0\0\u15e0\0\144\0\144\0\144\0\u1612"+
    "\0\u1644\0\u1676\0\u16a8\0\144\0\u16da\0\u170c\0\u173e\0\u1770"+
    "\0\144\0\u17a2\0\144\0\u17d4\0\u1806\0\u1838\0\u186a\0\144"+
    "\0\144\0\144\0\u189c\0\144\0\u18ce\0\144\0\144\0\u1900"+
    "\0\u1932\0\u1964\0\u1996\0\u19c8\0\u19fa\0\u1a2c\0\144\0\144"+
    "\0\62\0\u1a5e\0\144\0\144\0\u1a90\0\u1ac2\0\u1af4\0\u1b26"+
    "\0\144\0\144\0\144\0\u1b58\0\144\0\144\0\144";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\2\3"+
    "\1\11\1\12\1\13\1\14\1\3\1\15\1\16\1\17"+
    "\1\20\1\3\1\21\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\3\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\3\1\43\1\3"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\63\0\2\3\1\0\13\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\6\0\2\55\1\4"+
    "\15\55\1\0\41\55\3\0\1\5\57\0\2\3\1\0"+
    "\1\3\1\56\11\3\3\0\1\57\1\3\2\0\5\3"+
    "\13\0\1\60\2\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\61\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\10\3\1\62"+
    "\2\3\3\0\2\3\2\0\2\3\1\63\2\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\6\3\1\64"+
    "\4\3\3\0\2\3\2\0\3\3\1\65\1\66\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\1\3\1\67"+
    "\11\3\3\0\2\3\2\0\5\3\13\0\1\70\2\3"+
    "\2\0\1\3\7\0\2\3\1\0\10\3\1\71\2\3"+
    "\3\0\1\72\1\3\2\0\1\3\1\73\3\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\3\3\1\74"+
    "\7\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\3\3\1\75\3\3\1\76"+
    "\3\3\3\0\1\77\1\3\2\0\4\3\1\100\13\0"+
    "\3\3\2\0\1\3\6\0\20\16\1\0\41\16\1\0"+
    "\2\3\1\0\5\3\1\101\2\3\1\102\2\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\2\3\1\103\10\3\3\0\1\104\1\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\3\3\1\105\7\3\3\0\1\106\1\3\2\0"+
    "\2\3\1\107\2\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\1\110\1\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\13\3"+
    "\3\0\2\3\2\0\4\3\1\111\13\0\3\3\2\0"+
    "\1\3\41\0\1\112\1\113\61\0\1\114\61\0\1\115"+
    "\1\116\60\0\1\117\1\0\1\120\25\0\1\4\31\0"+
    "\1\121\2\0\1\122\15\0\1\123\40\0\1\124\61\0"+
    "\1\125\61\0\1\126\71\0\1\127\62\0\1\130\15\0"+
    "\2\3\1\0\3\3\1\131\7\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\13\3\3\0\1\132\1\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\10\0\1\133\60\0\2\3\1\0\2\3"+
    "\1\134\10\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\13\3\3\0\1\135"+
    "\1\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\6\3\1\136\4\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\6\3\1\137\2\3\1\140\1\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\13\3\3\0\2\3\2\0\1\141\4\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\5\3\1\142\5\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\1\3\1\143\11\3\3\0\2\3"+
    "\2\0\1\144\4\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\7\3\1\145\3\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\13\3\3\0\1\146\1\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\13\3\3\0\1\3"+
    "\1\147\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\2\3\2\0\5\3\13\0"+
    "\2\3\1\150\2\0\1\3\7\0\2\3\1\0\6\3"+
    "\1\151\3\3\1\152\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\5\3\1\153"+
    "\5\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\13\3\3\0\2\3\2\0"+
    "\5\3\13\0\1\3\1\154\1\3\2\0\1\3\7\0"+
    "\2\3\1\0\5\3\1\155\5\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\10\3\1\156\2\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\10\3\1\157"+
    "\2\3\3\0\1\3\1\160\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\3\3\1\161\7\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\7\3\1\162\3\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\5\3\1\163\5\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\13\3"+
    "\3\0\2\3\2\0\1\3\1\164\3\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\13\3\3\0\1\3"+
    "\1\165\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\2\3\2\0\2\3\1\166"+
    "\2\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\1\3\1\167\11\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\1\170\1\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\10\3\1\171\2\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\7\3\1\172\3\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\10\0\1\173\60\0\2\3"+
    "\1\0\7\3\1\174\3\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\7\3"+
    "\1\175\3\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\3\3\1\176\7\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\13\3\3\0\2\3\2\0\2\3"+
    "\1\177\2\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\2\3\1\200\10\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\13\3"+
    "\3\0\1\3\1\201\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\7\3\1\202\3\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\2\3\2\0\2\3\1\203"+
    "\2\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\204\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\7\3\1\205"+
    "\3\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\6\3\1\206\4\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\1\3\1\207\11\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\210\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\2\3\1\211"+
    "\10\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\13\3\3\0\2\3\2\0"+
    "\2\3\1\212\2\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\6\3\1\213\4\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\214\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\2\3\1\215"+
    "\10\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\5\3\1\216\1\217\4\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\6\3\1\220\4\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\1\3\1\221\11\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\10\3"+
    "\1\222\2\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\7\3\1\223\3\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\3\3\1\224\3\3\1\225\3\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\1\226\12\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\5\3\1\227\5\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\3\3\1\230"+
    "\7\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\11\3\1\231\1\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\2\3\2\0\2\3\1\232"+
    "\2\3\13\0\3\3\2\0\1\3\6\0\2\233\1\173"+
    "\15\233\1\0\35\233\1\234\3\233\1\0\2\3\1\0"+
    "\10\3\1\235\2\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\2\3\2\0\1\236\4\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\4\3\1\237\6\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\1\3\1\240\11\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\5\3"+
    "\1\241\5\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\10\3\1\242\2\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\12\3\1\243\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\6\3\1\244\4\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\2\3\2\0\1\245\4\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\13\3\3\0\1\3\1\246\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\1\3\1\247\11\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\5\3\1\250"+
    "\5\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\6\3\1\251\4\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\7\3\1\252\3\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\11\3\1\253\1\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\11\3\1\254"+
    "\1\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\13\3\3\0\1\3\1\255"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\10\3\1\256\2\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\13\3"+
    "\3\0\2\3\2\0\2\3\1\257\2\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\2\3\1\260\10\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\6\3\1\261\4\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\2\3\1\262\10\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\10\0\1\263\60\0\2\3"+
    "\1\0\10\3\1\264\2\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\6\3"+
    "\1\265\4\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\11\3\1\266\1\3"+
    "\3\0\2\3\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\13\3\3\0\2\3\2\0\4\3"+
    "\1\267\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\270\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\2\3\2\0\1\271\4\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\2\3\1\272\10\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\13\3\3\0\2\3\2\0\5\3\13\0\2\3"+
    "\1\273\2\0\1\3\7\0\2\3\1\0\10\3\1\274"+
    "\2\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\10\3\1\275\2\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\13\3\3\0\2\3\2\0\2\3\1\276"+
    "\2\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\277\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\2\3\1\300"+
    "\10\3\3\0\2\3\2\0\5\3\13\0\3\3\2\0"+
    "\1\3\10\0\1\263\53\0\1\301\4\0\2\3\1\0"+
    "\2\3\1\302\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\2\3\2\0\1\3\1\303\3\3\13\0\3\3\2\0"+
    "\1\3\7\0\2\3\1\0\2\3\1\304\10\3\3\0"+
    "\2\3\2\0\5\3\13\0\3\3\2\0\1\3\7\0"+
    "\2\3\1\0\3\3\1\305\7\3\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\3\3\1\306\7\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\1\3\1\307\2\0\5\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\2\3\1\310\10\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\7\0\2\3"+
    "\1\0\6\3\1\311\4\3\3\0\2\3\2\0\5\3"+
    "\13\0\3\3\2\0\1\3\7\0\2\3\1\0\1\3"+
    "\1\312\11\3\3\0\2\3\2\0\5\3\13\0\3\3"+
    "\2\0\1\3\7\0\2\3\1\0\13\3\3\0\2\3"+
    "\2\0\5\3\13\0\1\3\1\313\1\3\2\0\1\3"+
    "\7\0\2\3\1\0\12\3\1\314\3\0\2\3\2\0"+
    "\5\3\13\0\3\3\2\0\1\3\7\0\2\3\1\0"+
    "\2\3\1\315\10\3\3\0\2\3\2\0\5\3\13\0"+
    "\3\3\2\0\1\3\7\0\2\3\1\0\13\3\3\0"+
    "\2\3\2\0\1\316\4\3\13\0\3\3\2\0\1\3"+
    "\7\0\2\3\1\0\2\3\1\317\10\3\3\0\2\3"+
    "\2\0\5\3\13\0\3\3\2\0\1\3\6\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[7050];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\14\1\2\11\1\1\2\11\14\1\1\11"+
    "\3\1\2\11\1\1\6\11\1\0\34\1\11\11\1\0"+
    "\5\11\42\1\1\0\37\1\1\0\27\1\1\0\15\1"+
    "\1\11\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[207];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    public String lexemas;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexico(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexico(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 132) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 21: 
          { lexemas=yytext(); return Llave_c;
          }
        case 79: break;
        case 66: 
          { lexemas=yytext(); return Return;
          }
        case 80: break;
        case 12: 
          { lexemas=yytext(); return Suma;
          }
        case 81: break;
        case 47: 
          { lexemas=yytext(); return For;
          }
        case 82: break;
        case 33: 
          { lexemas=yytext(); return MenorIgual;
          }
        case 83: break;
        case 17: 
          { lexemas=yytext(); return DosPuntos;
          }
        case 84: break;
        case 15: 
          { lexemas=yytext(); return Negador;
          }
        case 85: break;
        case 68: 
          { lexemas=yytext(); return Switch;
          }
        case 86: break;
        case 13: 
          { lexemas=yytext(); return Resta;
          }
        case 87: break;
        case 6: 
          { lexemas=yytext(); return Comillas;
          }
        case 88: break;
        case 31: 
          { lexemas=yytext(); return MayorIgual;
          }
        case 89: break;
        case 22: 
          { lexemas=yytext(); return Numeral;
          }
        case 90: break;
        case 63: 
          { lexemas=yytext(); return False;
          }
        case 91: break;
        case 10: 
          { lexemas=yytext(); return Igual;
          }
        case 92: break;
        case 56: 
          { lexemas=yytext(); return Long;
          }
        case 93: break;
        case 14: 
          { lexemas=yytext(); return Multiplicacion;
          }
        case 94: break;
        case 4: 
          { /*Ignore*/
          }
        case 95: break;
        case 48: 
          { lexemas=yytext(); return Bool;
          }
        case 96: break;
        case 71: 
          { lexemas=yytext(); return Typedef;
          }
        case 97: break;
        case 28: 
          { lexemas=yytext(); return If;
          }
        case 98: break;
        case 75: 
          { lexemas=yytext(); return Iostream;
          }
        case 99: break;
        case 72: 
          { lexemas=yytext(); return Include;
          }
        case 100: break;
        case 64: 
          { lexemas=yytext(); return Float;
          }
        case 101: break;
        case 55: 
          { lexemas=yytext(); return Char;
          }
        case 102: break;
        case 20: 
          { lexemas=yytext(); return Llave_a;
          }
        case 103: break;
        case 69: 
          { lexemas=yytext(); return Define;
          }
        case 104: break;
        case 1: 
          { return ERROR;
          }
        case 105: break;
        case 26: 
          { lexemas=yytext(); return Punto;
          }
        case 106: break;
        case 77: 
          { lexemas=yytext(); return Unsigned;
          }
        case 107: break;
        case 19: 
          { lexemas=yytext(); return BitOr;
          }
        case 108: break;
        case 8: 
          { lexemas=yytext(); return Corchete_c;
          }
        case 109: break;
        case 74: 
          { lexemas=yytext(); return Register;
          }
        case 110: break;
        case 36: 
          { lexemas=yytext(); return Incremento;
          }
        case 111: break;
        case 49: 
          { lexemas=yytext(); return Byte;
          }
        case 112: break;
        case 73: 
          { lexemas=yytext(); return Default;
          }
        case 113: break;
        case 34: 
          { lexemas=yytext(); return DobleMenor;
          }
        case 114: break;
        case 16: 
          { lexemas=yytext(); return Modulo;
          }
        case 115: break;
        case 44: 
          { lexemas=yytext(); return Std;
          }
        case 116: break;
        case 54: 
          { lexemas=yytext(); return Cout;
          }
        case 117: break;
        case 42: 
          { lexemas=yytext(); return Y_logico;
          }
        case 118: break;
        case 30: 
          { lexemas=yytext(); return DobleMayor;
          }
        case 119: break;
        case 60: 
          { lexemas=yytext(); return Short;
          }
        case 120: break;
        case 35: 
          { lexemas=yytext(); return MasIgual;
          }
        case 121: break;
        case 51: 
          { lexemas=yytext(); return Else;
          }
        case 122: break;
        case 24: 
          { lexemas=yytext(); return Parent_c;
          }
        case 123: break;
        case 57: 
          { lexemas=yytext(); return Main;
          }
        case 124: break;
        case 2: 
          { lexemas=yytext(); return Identificador;
          }
        case 125: break;
        case 25: 
          { lexemas=yytext(); return P_coma;
          }
        case 126: break;
        case 40: 
          { lexemas=yytext(); return Diferente;
          }
        case 127: break;
        case 65: 
          { lexemas=yytext(); return While;
          }
        case 128: break;
        case 53: 
          { lexemas=yytext(); return Case;
          }
        case 129: break;
        case 11: 
          { lexemas=yytext(); return MenorQue;
          }
        case 130: break;
        case 38: 
          { lexemas=yytext(); return Decremento;
          }
        case 131: break;
        case 5: 
          { return Linea;
          }
        case 132: break;
        case 41: 
          { lexemas=yytext(); return ModuloIgual;
          }
        case 133: break;
        case 7: 
          { lexemas=yytext(); return Corchete_a;
          }
        case 134: break;
        case 61: 
          { lexemas=yytext(); return Const;
          }
        case 135: break;
        case 78: 
          { lexemas=yytext(); return Namespace;
          }
        case 136: break;
        case 18: 
          { lexemas=yytext(); return BitAnd;
          }
        case 137: break;
        case 46: 
          { lexemas=yytext(); return Cin;
          }
        case 138: break;
        case 37: 
          { lexemas=yytext(); return MenosIgual;
          }
        case 139: break;
        case 32: 
          { lexemas=yytext(); return ComparadorIgual;
          }
        case 140: break;
        case 52: 
          { lexemas=yytext(); return True;
          }
        case 141: break;
        case 45: 
          { lexemas=yytext(); return Int;
          }
        case 142: break;
        case 59: 
          { lexemas=yytext(); return Break;
          }
        case 143: break;
        case 67: 
          { lexemas=yytext(); return Cadena;
          }
        case 144: break;
        case 27: 
          { lexemas=yytext(); return Coma;
          }
        case 145: break;
        case 62: 
          { lexemas=yytext(); return Using;
          }
        case 146: break;
        case 9: 
          { lexemas=yytext(); return MayorQue;
          }
        case 147: break;
        case 3: 
          { lexemas=yytext(); return Numero;
          }
        case 148: break;
        case 43: 
          { lexemas=yytext(); return O_logico;
          }
        case 149: break;
        case 58: 
          { lexemas=yytext(); return Void;
          }
        case 150: break;
        case 23: 
          { lexemas=yytext(); return Parent_a;
          }
        case 151: break;
        case 39: 
          { lexemas=yytext(); return MultiplicacionIgual;
          }
        case 152: break;
        case 70: 
          { lexemas=yytext(); return Double;
          }
        case 153: break;
        case 29: 
          { lexemas=yytext(); return Do;
          }
        case 154: break;
        case 50: 
          { lexemas=yytext(); return Endl;
          }
        case 155: break;
        case 76: 
          { lexemas=yytext(); return Continue;
          }
        case 156: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
