
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Jun 15 07:20:01 COT 2022
//----------------------------------------------------

package Analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Return = 69;
  public static final int Llave_c = 45;
  public static final int Incremento = 41;
  public static final int ComparadorIgual = 12;
  public static final int Llave_a = 44;
  public static final int Std = 72;
  public static final int Linea = 43;
  public static final int Break = 4;
  public static final int Coma = 10;
  public static final int Parent_c = 64;
  public static final int Parent_a = 63;
  public static final int Corchete_c = 16;
  public static final int True = 76;
  public static final int MenorQue = 51;
  public static final int Corchete_a = 15;
  public static final int Long = 46;
  public static final int Punto = 66;
  public static final int Default = 18;
  public static final int Char = 8;
  public static final int Decremento = 20;
  public static final int For = 35;
  public static final int BitAnd = 2;
  public static final int Et = 32;
  public static final int Void = 79;
  public static final int DosPuntos = 28;
  public static final int Else = 29;
  public static final int Negador = 59;
  public static final int Resta = 68;
  public static final int BitOr = 3;
  public static final int Int = 39;
  public static final int Cin = 9;
  public static final int Using = 78;
  public static final int Suma = 71;
  public static final int Y_logico = 81;
  public static final int ERROR = 31;
  public static final int DobleMenor = 27;
  public static final int Cadena = 6;
  public static final int Typedef = 75;
  public static final int MenorIgual = 53;
  public static final int Main = 47;
  public static final int Do = 24;
  public static final int P_coma = 65;
  public static final int Unsigned = 77;
  public static final int MayorQue = 50;
  public static final int MasIgual = 48;
  public static final int MultiplicacionIgual = 57;
  public static final int Short = 70;
  public static final int MenosIgual = 49;
  public static final int Case = 7;
  public static final int Const = 13;
  public static final int ModuloIgual = 55;
  public static final int Endl = 30;
  public static final int DivisionIgual = 23;
  public static final int Continue = 14;
  public static final int Byte = 5;
  public static final int Numeral = 61;
  public static final int If = 37;
  public static final int MayorIgual = 52;
  public static final int O_logico = 62;
  public static final int Define = 19;
  public static final int EOF = 0;
  public static final int Cout = 17;
  public static final int Numero = 60;
  public static final int Double = 25;
  public static final int Struct = 73;
  public static final int Division = 22;
  public static final int Namespace = 58;
  public static final int error = 1;
  public static final int False = 33;
  public static final int Diferente = 21;
  public static final int Comillas = 11;
  public static final int Float = 34;
  public static final int Iostream = 42;
  public static final int Identificador = 36;
  public static final int DobleMayor = 26;
  public static final int Include = 40;
  public static final int Modulo = 54;
  public static final int Register = 67;
  public static final int Igual = 38;
  public static final int While = 80;
  public static final int Switch = 74;
  public static final int Multiplicacion = 56;
}

